# Triggers

on:
  push:
    branches:
      - main
  pull_request:
    branches:
    - Stage
jobs:
  build:
    name: Deploy project with Nginx
    runs-on: ubuntu-latest
    steps:

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install NPM Dependencies
      run: npm install
      
    - name: Build NPM Assets 
      run: npm run build
      
    - name: Deploy using SSH
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.HOST }}
        username:  ${{ secrets.USERNAME }}
        key:  ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        passphrase: ${{ secrets.PASSPHRASE }}
        script: | 
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh
          cd /home/react-app/goshehartvitereactapp/
          ls -al
          ls -al ~/.ssh
          git pull origin main
          git status
          cp -r dist/* /var/www/html
          echo "zigi plz"
