# Triggers
name: deploy goshehartvitereactapp
on:
  push:
    branches:
      - main
  pull_request:
    branches:
    - Stage
    
jobs:
  build:
    name: Deploy project with Nginx
    runs-on: self-hosted
   # runs-on: ubuntu-latest
    steps:
    - name: Deploy using SSH
    - uses: actions/checkout@v2
      with:
        node-version: ${{ matrix.node-version }}
      #  host: ${{ secrets.HOST }}
      #  username:  ${{ secrets.USERNAME }}
      #  key:  ${{ secrets.SSH_PRIVATE_KEY }}
      #  passphrase: ${{ secrets.PASSPHRASE }}
      #  port: ${{ secrets.PORT }} 
      # uses: actions/setup-node@v1
    - name: Run script
    - run: |
        npm i
        npm run build

# every step must define a `uses` or `run` key
