# Triggers
name: Deploy goshehartvitereactapp to Staging
on:
  push:
    branches:
      - stage

jobs:
  build:
    name: Deploy project with Nginx
    runs-on: [self-hosted, Staging]
    # runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Set Environment Variables
        run: |
          echo "VITE_API_URL=${{ secrets.VITE_ENVIRONMENT_STAGING }}" >> $GITHUB_ENV
      - name: NPM Build
        run: |
          npm i
          npm run build -- --mode staging
          ls -a 
          cp -a dist/. /var/www/goshehartreact-staging
          cd ..
      - name: PM2 Syncing
        run: |
          export PM2_HOME=/root/.pm2
          pm2 resurrect
          pm2 stop goshehartreactviteapp-staging
          pm2 start goshehartreactviteapp-staging
          pm2 save
      - name: Starting NGNIX
        run: |
          service nginx restart
