# Triggers
name: deploy goshehartvitereactapp
on:
  push:
    branches:
      - main
  pull_request:
    branches:
    - Stage
    
jobs:
  build:
    name: Deploy project with Nginx
    runs-on: self-hosted
   # runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        npm i
        npm run build
        ls -a 
        cp -a dist/. /var/www/html
        cd ..
        pm2 stop goshehartreactviteapp
        pm2 start goshehartreactviteapp
        pm2 save
        service nginx restart
