# Triggers

on:
  push:
    branches:
      - main
  pull_request:
    branches:
    - Stage
# Functions
jobs:
  # Build Job
  build:
    # Name of the job
    name: Build
    # The OS to run the job on
    runs-on: ubuntu-latest
    # Steps
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with: 
          fetch-depth: 2
      - name: Install node 19
        uses: actions/setup-node@v4
        with:
          node-version: 19.x
      - name: Install NPM Dependencies
        run: npm i
      - name: Build Project
        run: npm run build
      - name: Upload artifact in order to deploy
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./dist
  # Deploy Job
  deploy:
    name: 🚚 Deploy
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./dist
      - name: 📂 Deploy to cPanel
        uses: SamKirkland/FTP-Deploy-Action@master
        with:
          server: ${{ secrets.SERVER }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.ZIGISECRET }}
          # server-dir: ${{ secrets.DIRECTORY }}
          protocol: ${{ secrets.PROTOCOL }}
          local-dir: dist/
          server-dir: ./public_html/
